///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace OwnTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OwnTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e2c85e03-6898-42bb-9704-9b7516a9fce5")]
    public partial class OwnTestRepository : RepoGenBaseFolder
    {
        static OwnTestRepository instance = new OwnTestRepository();
        OwnTestRepositoryFolders.DEMOQAAppFolder _demoqa;

        /// <summary>
        /// Gets the singleton class instance representing the OwnTestRepository element repository.
        /// </summary>
        [RepositoryFolder("e2c85e03-6898-42bb-9704-9b7516a9fce5")]
        public static OwnTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OwnTestRepository() 
            : base("OwnTestRepository", "/", null, 0, false, "e2c85e03-6898-42bb-9704-9b7516a9fce5", ".\\RepositoryImages\\OwnTestRepositorye2c85e03.rximgres")
        {
            _demoqa = new OwnTestRepositoryFolders.DEMOQAAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e2c85e03-6898-42bb-9704-9b7516a9fce5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DEMOQA folder.
        /// </summary>
        [RepositoryFolder("9ebacf0c-f15e-4b1e-b006-9d4a2b446f87")]
        public virtual OwnTestRepositoryFolders.DEMOQAAppFolder DEMOQA
        {
            get { return _demoqa; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class OwnTestRepositoryFolders
    {
        /// <summary>
        /// The DEMOQAAppFolder folder.
        /// </summary>
        [RepositoryFolder("9ebacf0c-f15e-4b1e-b006-9d4a2b446f87")]
        public partial class DEMOQAAppFolder : RepoGenBaseFolder
        {
            OwnTestRepositoryFolders.MenuListFolder _menulist;
            OwnTestRepositoryFolders.CategoryCardsFolder _categorycards;
            RepoItemInfo _cardupInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _permanentaddressInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _rcticonrcticonuncheckInfo;
            RepoItemInfo _youhaveselectedInfo;
            RepoItemInfo _noradioInfo;
            RepoItemInfo _doubleclickbtnInfo;
            RepoItemInfo _rightclickbtnInfo;
            RepoItemInfo _neyduInfo;

            /// <summary>
            /// Creates a new DEMOQA  folder.
            /// </summary>
            public DEMOQAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DEMOQA", "/dom[@domain='demoqa.com']", parentFolder, 30000, null, false, "9ebacf0c-f15e-4b1e-b006-9d4a2b446f87", "")
            {
                _menulist = new OwnTestRepositoryFolders.MenuListFolder(this);
                _categorycards = new OwnTestRepositoryFolders.CategoryCardsFolder(this);
                _cardupInfo = new RepoItemInfo(this, "CardUp", ".//div[#'app']/div/div/div[2]/div/div[1]/div/div[1]", ".//div[#'app']/div/div/div[2]/div/div[1]/div/div[1]", 30000, null, "e5820fd0-94a0-43cb-81b4-6d28731733a8");
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'userName']", ".//input[#'userName']", 30000, null, "bd8d5490-82bd-45a8-b3e7-2c6a7beb94e6");
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'userEmail']", ".//input[#'userEmail']", 30000, null, "14832f90-57f7-43b0-b8ca-f77c21b0764d");
                _permanentaddressInfo = new RepoItemInfo(this, "PermanentAddress", ".//textarea[#'permanentAddress']", ".//textarea[#'permanentAddress']", 30000, null, "08b44309-5485-4be6-bd69-e6edbeb97e70");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//button[#'submit']", ".//button[#'submit']", 30000, null, "55bc434c-f65c-4444-816a-89c1aeb0f6a0");
                _rcticonrcticonuncheckInfo = new RepoItemInfo(this, "RctIconRctIconUncheck", ".//div[#'tree-node']/ol//label/span[1]/svg", ".//div[#'tree-node']//label/span[1]/svg", 30000, null, "2d7623a7-33d0-47c2-b50b-1d1df66cd519");
                _youhaveselectedInfo = new RepoItemInfo(this, "YouHaveSelected", ".//div[#'result']/span[@innertext='You have selected :']", ".//div[#'result']/span[@innertext='You have selected :']", 30000, null, "693bce69-6051-49f4-8642-2f2fe18f58d5");
                _noradioInfo = new RepoItemInfo(this, "NoRadio", ".//input[#'noRadio']", ".//input[#'noRadio']", 30000, null, "c70e571e-c744-4013-9956-836392800fd0");
                _doubleclickbtnInfo = new RepoItemInfo(this, "DoubleClickBtn", ".//button[#'doubleClickBtn']", ".//button[#'doubleClickBtn']", 30000, null, "5b2531f6-b8f4-4dce-a93e-bb9fa912cb07");
                _rightclickbtnInfo = new RepoItemInfo(this, "RightClickBtn", ".//button[#'rightClickBtn']", ".//button[#'rightClickBtn']", 30000, null, "4acbdbdf-ef15-493a-a6f9-18d60786ebfa");
                _neyduInfo = new RepoItemInfo(this, "NEyDU", ".//button[#'nEyDU']", ".//button[#'nEyDU']", 30000, null, "d276485b-e7ae-434c-93e9-643800a85875");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9ebacf0c-f15e-4b1e-b006-9d4a2b446f87")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9ebacf0c-f15e-4b1e-b006-9d4a2b446f87")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CardUp item.
            /// </summary>
            [RepositoryItem("e5820fd0-94a0-43cb-81b4-6d28731733a8")]
            public virtual Ranorex.DivTag CardUp
            {
                get
                {
                    return _cardupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CardUp item info.
            /// </summary>
            [RepositoryItemInfo("e5820fd0-94a0-43cb-81b4-6d28731733a8")]
            public virtual RepoItemInfo CardUpInfo
            {
                get
                {
                    return _cardupInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("bd8d5490-82bd-45a8-b3e7-2c6a7beb94e6")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("bd8d5490-82bd-45a8-b3e7-2c6a7beb94e6")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("14832f90-57f7-43b0-b8ca-f77c21b0764d")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("14832f90-57f7-43b0-b8ca-f77c21b0764d")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The PermanentAddress item.
            /// </summary>
            [RepositoryItem("08b44309-5485-4be6-bd69-e6edbeb97e70")]
            public virtual Ranorex.TextAreaTag PermanentAddress
            {
                get
                {
                    return _permanentaddressInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The PermanentAddress item info.
            /// </summary>
            [RepositoryItemInfo("08b44309-5485-4be6-bd69-e6edbeb97e70")]
            public virtual RepoItemInfo PermanentAddressInfo
            {
                get
                {
                    return _permanentaddressInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("55bc434c-f65c-4444-816a-89c1aeb0f6a0")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("55bc434c-f65c-4444-816a-89c1aeb0f6a0")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The RctIconRctIconUncheck item.
            /// </summary>
            [RepositoryItem("2d7623a7-33d0-47c2-b50b-1d1df66cd519")]
            public virtual Ranorex.SvgTag RctIconRctIconUncheck
            {
                get
                {
                    return _rcticonrcticonuncheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The RctIconRctIconUncheck item info.
            /// </summary>
            [RepositoryItemInfo("2d7623a7-33d0-47c2-b50b-1d1df66cd519")]
            public virtual RepoItemInfo RctIconRctIconUncheckInfo
            {
                get
                {
                    return _rcticonrcticonuncheckInfo;
                }
            }

            /// <summary>
            /// The YouHaveSelected item.
            /// </summary>
            [RepositoryItem("693bce69-6051-49f4-8642-2f2fe18f58d5")]
            public virtual Ranorex.SpanTag YouHaveSelected
            {
                get
                {
                    return _youhaveselectedInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The YouHaveSelected item info.
            /// </summary>
            [RepositoryItemInfo("693bce69-6051-49f4-8642-2f2fe18f58d5")]
            public virtual RepoItemInfo YouHaveSelectedInfo
            {
                get
                {
                    return _youhaveselectedInfo;
                }
            }

            /// <summary>
            /// The NoRadio item.
            /// </summary>
            [RepositoryItem("c70e571e-c744-4013-9956-836392800fd0")]
            public virtual Ranorex.InputTag NoRadio
            {
                get
                {
                    return _noradioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NoRadio item info.
            /// </summary>
            [RepositoryItemInfo("c70e571e-c744-4013-9956-836392800fd0")]
            public virtual RepoItemInfo NoRadioInfo
            {
                get
                {
                    return _noradioInfo;
                }
            }

            /// <summary>
            /// The DoubleClickBtn item.
            /// </summary>
            [RepositoryItem("5b2531f6-b8f4-4dce-a93e-bb9fa912cb07")]
            public virtual Ranorex.ButtonTag DoubleClickBtn
            {
                get
                {
                    return _doubleclickbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The DoubleClickBtn item info.
            /// </summary>
            [RepositoryItemInfo("5b2531f6-b8f4-4dce-a93e-bb9fa912cb07")]
            public virtual RepoItemInfo DoubleClickBtnInfo
            {
                get
                {
                    return _doubleclickbtnInfo;
                }
            }

            /// <summary>
            /// The RightClickBtn item.
            /// </summary>
            [RepositoryItem("4acbdbdf-ef15-493a-a6f9-18d60786ebfa")]
            public virtual Ranorex.ButtonTag RightClickBtn
            {
                get
                {
                    return _rightclickbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RightClickBtn item info.
            /// </summary>
            [RepositoryItemInfo("4acbdbdf-ef15-493a-a6f9-18d60786ebfa")]
            public virtual RepoItemInfo RightClickBtnInfo
            {
                get
                {
                    return _rightclickbtnInfo;
                }
            }

            /// <summary>
            /// The NEyDU item.
            /// </summary>
            [RepositoryItem("d276485b-e7ae-434c-93e9-643800a85875")]
            public virtual Ranorex.ButtonTag NEyDU
            {
                get
                {
                    return _neyduInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The NEyDU item info.
            /// </summary>
            [RepositoryItemInfo("d276485b-e7ae-434c-93e9-643800a85875")]
            public virtual RepoItemInfo NEyDUInfo
            {
                get
                {
                    return _neyduInfo;
                }
            }

            /// <summary>
            /// The MenuList folder.
            /// </summary>
            [RepositoryFolder("74975da2-1e3b-4368-ae55-bd97a810cafc")]
            public virtual OwnTestRepositoryFolders.MenuListFolder MenuList
            {
                get { return _menulist; }
            }

            /// <summary>
            /// The CategoryCards folder.
            /// </summary>
            [RepositoryFolder("28f737b7-c85e-4f05-b092-a7e6eb5b4729")]
            public virtual OwnTestRepositoryFolders.CategoryCardsFolder CategoryCards
            {
                get { return _categorycards; }
            }
        }

        /// <summary>
        /// The MenuListFolder folder.
        /// </summary>
        [RepositoryFolder("74975da2-1e3b-4368-ae55-bd97a810cafc")]
        public partial class MenuListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textboxInfo;
            RepoItemInfo _checkboxInfo;
            RepoItemInfo _radiobuttonInfo;
            RepoItemInfo _webtablesInfo;
            RepoItemInfo _buttonsInfo;

            /// <summary>
            /// Creates a new MenuList  folder.
            /// </summary>
            public MenuListFolder(RepoGenBaseFolder parentFolder) :
                    base("MenuList", ".//div[#'app']/div/div/div/div[1]/div/div/div[1]/?/?/ul", parentFolder, 30000, null, false, "74975da2-1e3b-4368-ae55-bd97a810cafc", "")
            {
                _textboxInfo = new RepoItemInfo(this, "TextBox", "li[1]/span[@innertext='Text Box']", "", 30000, null, "6e7d283b-a56e-48bd-956a-98853a08d995");
                _checkboxInfo = new RepoItemInfo(this, "CheckBox", "li[2]/span[@innertext='Check Box']", "", 30000, null, "5dc9ff30-1b7f-4218-8c63-193b404e8c23");
                _radiobuttonInfo = new RepoItemInfo(this, "RadioButton", "li[3]/span[@innertext='Radio Button']", "", 30000, null, "5b1f2d6f-fb1c-4ab6-980d-5ccb47e6cee8");
                _webtablesInfo = new RepoItemInfo(this, "WebTables", "li[4]/span[@innertext='Web Tables']", "", 30000, null, "782a9751-c036-4fb3-b994-2620b8e13131");
                _buttonsInfo = new RepoItemInfo(this, "Buttons", "li[5]/span[@innertext='Buttons']", "", 30000, null, "412543e1-12e7-40d6-a4b4-e6ead002ac88");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("74975da2-1e3b-4368-ae55-bd97a810cafc")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("74975da2-1e3b-4368-ae55-bd97a810cafc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextBox item.
            /// </summary>
            [RepositoryItem("6e7d283b-a56e-48bd-956a-98853a08d995")]
            public virtual Ranorex.SpanTag TextBox
            {
                get
                {
                    return _textboxInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TextBox item info.
            /// </summary>
            [RepositoryItemInfo("6e7d283b-a56e-48bd-956a-98853a08d995")]
            public virtual RepoItemInfo TextBoxInfo
            {
                get
                {
                    return _textboxInfo;
                }
            }

            /// <summary>
            /// The CheckBox item.
            /// </summary>
            [RepositoryItem("5dc9ff30-1b7f-4218-8c63-193b404e8c23")]
            public virtual Ranorex.SpanTag CheckBox
            {
                get
                {
                    return _checkboxInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckBox item info.
            /// </summary>
            [RepositoryItemInfo("5dc9ff30-1b7f-4218-8c63-193b404e8c23")]
            public virtual RepoItemInfo CheckBoxInfo
            {
                get
                {
                    return _checkboxInfo;
                }
            }

            /// <summary>
            /// The RadioButton item.
            /// </summary>
            [RepositoryItem("5b1f2d6f-fb1c-4ab6-980d-5ccb47e6cee8")]
            public virtual Ranorex.SpanTag RadioButton
            {
                get
                {
                    return _radiobuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RadioButton item info.
            /// </summary>
            [RepositoryItemInfo("5b1f2d6f-fb1c-4ab6-980d-5ccb47e6cee8")]
            public virtual RepoItemInfo RadioButtonInfo
            {
                get
                {
                    return _radiobuttonInfo;
                }
            }

            /// <summary>
            /// The WebTables item.
            /// </summary>
            [RepositoryItem("782a9751-c036-4fb3-b994-2620b8e13131")]
            public virtual Ranorex.SpanTag WebTables
            {
                get
                {
                    return _webtablesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WebTables item info.
            /// </summary>
            [RepositoryItemInfo("782a9751-c036-4fb3-b994-2620b8e13131")]
            public virtual RepoItemInfo WebTablesInfo
            {
                get
                {
                    return _webtablesInfo;
                }
            }

            /// <summary>
            /// The Buttons item.
            /// </summary>
            [RepositoryItem("412543e1-12e7-40d6-a4b4-e6ead002ac88")]
            public virtual Ranorex.SpanTag Buttons
            {
                get
                {
                    return _buttonsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Buttons item info.
            /// </summary>
            [RepositoryItemInfo("412543e1-12e7-40d6-a4b4-e6ead002ac88")]
            public virtual RepoItemInfo ButtonsInfo
            {
                get
                {
                    return _buttonsInfo;
                }
            }
        }

        /// <summary>
        /// The CategoryCardsFolder folder.
        /// </summary>
        [RepositoryFolder("28f737b7-c85e-4f05-b092-a7e6eb5b4729")]
        public partial class CategoryCardsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _col12colmd6mt4Info;
            RepoItemInfo _labeltagyesInfo;
            RepoItemInfo _cierraInfo;
            RepoItemInfo _impressiveInfo;
            RepoItemInfo _impressive1Info;
            RepoItemInfo _spantagyesInfo;

            /// <summary>
            /// Creates a new CategoryCards  folder.
            /// </summary>
            public CategoryCardsFolder(RepoGenBaseFolder parentFolder) :
                    base("CategoryCards", ".//div[#'app']/div/div/div/div[2]", parentFolder, 30000, null, false, "28f737b7-c85e-4f05-b092-a7e6eb5b4729", "")
            {
                _col12colmd6mt4Info = new RepoItemInfo(this, "Col12ColMd6Mt4", "", "", 30000, null, "4fc9d32b-1f50-4f70-b6af-e9f3aab9c254");
                _labeltagyesInfo = new RepoItemInfo(this, "LabelTagYes", "div[2]/div[2]/label[@innertext='Yes']", "", 30000, null, "086528c7-7bbe-47ba-8647-1d375048561a");
                _cierraInfo = new RepoItemInfo(this, "Cierra", "div[2]/div[3]/div[1]/div[2]/div[1]/?/?/div[@innertext='Cierra']", "", 30000, null, "59a663d2-3c6e-424f-ba58-df3e5cb3394f");
                _impressiveInfo = new RepoItemInfo(this, "Impressive", "div[2]/div[3]/label[@innertext='Impressive']", "", 30000, null, "c91b843f-9e11-4093-83ca-ce5fdd35a26d");
                _impressive1Info = new RepoItemInfo(this, "Impressive1", "div[2]/p[@innertext='You have selected ']/span[@innertext='Impressive']", "", 30000, null, "c3fbc628-24c1-49eb-95d6-ab533e6bc149");
                _spantagyesInfo = new RepoItemInfo(this, "SpanTagYes", "div[2]/p[@innertext='You have selected ']/span[@innertext='Yes']", "", 30000, null, "d63613ae-a623-4d7c-ae88-27a9f34d9dbd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28f737b7-c85e-4f05-b092-a7e6eb5b4729")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28f737b7-c85e-4f05-b092-a7e6eb5b4729")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Col12ColMd6Mt4 item.
            /// </summary>
            [RepositoryItem("4fc9d32b-1f50-4f70-b6af-e9f3aab9c254")]
            public virtual Ranorex.DivTag Col12ColMd6Mt4
            {
                get
                {
                    return _col12colmd6mt4Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Col12ColMd6Mt4 item info.
            /// </summary>
            [RepositoryItemInfo("4fc9d32b-1f50-4f70-b6af-e9f3aab9c254")]
            public virtual RepoItemInfo Col12ColMd6Mt4Info
            {
                get
                {
                    return _col12colmd6mt4Info;
                }
            }

            /// <summary>
            /// The LabelTagYes item.
            /// </summary>
            [RepositoryItem("086528c7-7bbe-47ba-8647-1d375048561a")]
            public virtual Ranorex.LabelTag LabelTagYes
            {
                get
                {
                    return _labeltagyesInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The LabelTagYes item info.
            /// </summary>
            [RepositoryItemInfo("086528c7-7bbe-47ba-8647-1d375048561a")]
            public virtual RepoItemInfo LabelTagYesInfo
            {
                get
                {
                    return _labeltagyesInfo;
                }
            }

            /// <summary>
            /// The Cierra item.
            /// </summary>
            [RepositoryItem("59a663d2-3c6e-424f-ba58-df3e5cb3394f")]
            public virtual Ranorex.DivTag Cierra
            {
                get
                {
                    return _cierraInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Cierra item info.
            /// </summary>
            [RepositoryItemInfo("59a663d2-3c6e-424f-ba58-df3e5cb3394f")]
            public virtual RepoItemInfo CierraInfo
            {
                get
                {
                    return _cierraInfo;
                }
            }

            /// <summary>
            /// The Impressive item.
            /// </summary>
            [RepositoryItem("c91b843f-9e11-4093-83ca-ce5fdd35a26d")]
            public virtual Ranorex.LabelTag Impressive
            {
                get
                {
                    return _impressiveInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The Impressive item info.
            /// </summary>
            [RepositoryItemInfo("c91b843f-9e11-4093-83ca-ce5fdd35a26d")]
            public virtual RepoItemInfo ImpressiveInfo
            {
                get
                {
                    return _impressiveInfo;
                }
            }

            /// <summary>
            /// The Impressive1 item.
            /// </summary>
            [RepositoryItem("c3fbc628-24c1-49eb-95d6-ab533e6bc149")]
            public virtual Ranorex.SpanTag Impressive1
            {
                get
                {
                    return _impressive1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Impressive1 item info.
            /// </summary>
            [RepositoryItemInfo("c3fbc628-24c1-49eb-95d6-ab533e6bc149")]
            public virtual RepoItemInfo Impressive1Info
            {
                get
                {
                    return _impressive1Info;
                }
            }

            /// <summary>
            /// The SpanTagYes item.
            /// </summary>
            [RepositoryItem("d63613ae-a623-4d7c-ae88-27a9f34d9dbd")]
            public virtual Ranorex.SpanTag SpanTagYes
            {
                get
                {
                    return _spantagyesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagYes item info.
            /// </summary>
            [RepositoryItemInfo("d63613ae-a623-4d7c-ae88-27a9f34d9dbd")]
            public virtual RepoItemInfo SpanTagYesInfo
            {
                get
                {
                    return _spantagyesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
