///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace OwnTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("e1c59d14-a1b6-4311-9380-c6fae24ff6a4", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the OwnTestRepository repository.
        /// </summary>
        public static OwnTestRepository repo = OwnTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.CardUp' at 197;72.", repo.DEMOQA.CardUpInfo, new RecordItemIndex(0));
            repo.DEMOQA.CardUp.Click("197;72");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.MenuList.TextBox' at 73;15.", repo.DEMOQA.MenuList.TextBoxInfo, new RecordItemIndex(1));
            repo.DEMOQA.MenuList.TextBox.Click("73;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DEMOQA' at 1905;180.", repo.DEMOQA.SelfInfo, new RecordItemIndex(2));
            repo.DEMOQA.Self.MoveTo("1905;180");
            repo.DEMOQA.Self.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DEMOQA' at 1906;411.", repo.DEMOQA.SelfInfo, new RecordItemIndex(3));
            repo.DEMOQA.Self.MoveTo("1906;411");
            repo.DEMOQA.Self.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.UserName' at 57;42.", repo.DEMOQA.UserNameInfo, new RecordItemIndex(4));
            repo.DEMOQA.UserName.Click("57;42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'navf' with focus on 'DEMOQA.UserName'.", repo.DEMOQA.UserNameInfo, new RecordItemIndex(5));
            repo.DEMOQA.UserName.PressKeys("navf");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ab' with focus on 'DEMOQA'.", repo.DEMOQA.SelfInfo, new RecordItemIndex(6));
            repo.DEMOQA.Self.EnsureVisible();
            Keyboard.Press("ab");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c' with focus on 'DEMOQA'.", repo.DEMOQA.SelfInfo, new RecordItemIndex(7));
            repo.DEMOQA.Self.EnsureVisible();
            Keyboard.Press("c");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.UserEmail' at 112;32.", repo.DEMOQA.UserEmailInfo, new RecordItemIndex(8));
            repo.DEMOQA.UserEmail.Click("112;32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}@{LShiftKey up}gmail.bij' with focus on 'DEMOQA.UserEmail'.", repo.DEMOQA.UserEmailInfo, new RecordItemIndex(9));
            repo.DEMOQA.UserEmail.PressKeys("{LShiftKey down}@{LShiftKey up}gmail.bij");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.UserEmail' at 152;122.", repo.DEMOQA.UserEmailInfo, new RecordItemIndex(10));
            repo.DEMOQA.UserEmail.Click("152;122");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'zsdv' with focus on 'DEMOQA'.", repo.DEMOQA.SelfInfo, new RecordItemIndex(11));
            repo.DEMOQA.Self.EnsureVisible();
            Keyboard.Press("zsdv");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.PermanentAddress' at 84;64.", repo.DEMOQA.PermanentAddressInfo, new RecordItemIndex(12));
            repo.DEMOQA.PermanentAddress.Click("84;64");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'swdrr' with focus on 'DEMOQA.PermanentAddress'.", repo.DEMOQA.PermanentAddressInfo, new RecordItemIndex(13));
            repo.DEMOQA.PermanentAddress.PressKeys("swdrr");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DEMOQA' at 1906;313.", repo.DEMOQA.SelfInfo, new RecordItemIndex(14));
            repo.DEMOQA.Self.MoveTo("1906;313");
            repo.DEMOQA.Self.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DEMOQA' at 1912;430.", repo.DEMOQA.SelfInfo, new RecordItemIndex(15));
            repo.DEMOQA.Self.MoveTo("1912;430");
            repo.DEMOQA.Self.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.Submit' at 59;20.", repo.DEMOQA.SubmitInfo, new RecordItemIndex(16));
            repo.DEMOQA.Submit.Click("59;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.MenuList.CheckBox' at 59;23.", repo.DEMOQA.MenuList.CheckBoxInfo, new RecordItemIndex(17));
            repo.DEMOQA.MenuList.CheckBox.Click("59;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 5}' with focus on 'DEMOQA'.", repo.DEMOQA.SelfInfo, new RecordItemIndex(18));
            repo.DEMOQA.Self.EnsureVisible();
            Keyboard.Press("{Down 5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.RctIconRctIconUncheck' at 14;18.", repo.DEMOQA.RctIconRctIconUncheckInfo, new RecordItemIndex(19));
            repo.DEMOQA.RctIconRctIconUncheck.Click("14;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='You have selected :') on item 'DEMOQA.YouHaveSelected'.", repo.DEMOQA.YouHaveSelectedInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.DEMOQA.YouHaveSelectedInfo, "InnerText", "You have selected :");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.MenuList.RadioButton' at 83;31.", repo.DEMOQA.MenuList.RadioButtonInfo, new RecordItemIndex(21));
            repo.DEMOQA.MenuList.RadioButton.Click("83;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DEMOQA' at 1907;166.", repo.DEMOQA.SelfInfo, new RecordItemIndex(22));
            repo.DEMOQA.Self.MoveTo("1907;166");
            repo.DEMOQA.Self.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DEMOQA' at 1904;364.", repo.DEMOQA.SelfInfo, new RecordItemIndex(23));
            repo.DEMOQA.Self.MoveTo("1904;364");
            repo.DEMOQA.Self.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.CategoryCards.LabelTagYes' at -26;21.", repo.DEMOQA.CategoryCards.LabelTagYesInfo, new RecordItemIndex(24));
            repo.DEMOQA.CategoryCards.LabelTagYes.Click("-26;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.CategoryCards.Col12ColMd6Mt4' at 702;851.", repo.DEMOQA.CategoryCards.Col12ColMd6Mt4Info, new RecordItemIndex(25));
            repo.DEMOQA.CategoryCards.Col12ColMd6Mt4.Click("702;851");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Yes') on item 'DEMOQA.CategoryCards.SpanTagYes'.", repo.DEMOQA.CategoryCards.SpanTagYesInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.DEMOQA.CategoryCards.SpanTagYesInfo, "InnerText", "Yes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.CategoryCards.Impressive' at -18;25.", repo.DEMOQA.CategoryCards.ImpressiveInfo, new RecordItemIndex(27));
            repo.DEMOQA.CategoryCards.Impressive.Click("-18;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Impressive') on item 'DEMOQA.CategoryCards.Impressive1'.", repo.DEMOQA.CategoryCards.Impressive1Info, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.DEMOQA.CategoryCards.Impressive1Info, "InnerText", "Impressive");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'DEMOQA.NoRadio'.", repo.DEMOQA.NoRadioInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.DEMOQA.NoRadioInfo, "Enabled", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='on') on item 'DEMOQA.NoRadio'.", repo.DEMOQA.NoRadioInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.DEMOQA.NoRadioInfo, "Value", "on");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.MenuList.WebTables' at 96;18.", repo.DEMOQA.MenuList.WebTablesInfo, new RecordItemIndex(31));
            repo.DEMOQA.MenuList.WebTables.Click("96;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA' at 1909;140.", repo.DEMOQA.SelfInfo, new RecordItemIndex(32));
            repo.DEMOQA.Self.Click("1909;140");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.MenuList.Buttons' at 48;12.", repo.DEMOQA.MenuList.ButtonsInfo, new RecordItemIndex(33));
            repo.DEMOQA.MenuList.Buttons.Click("48;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DEMOQA' at 1910;212.", repo.DEMOQA.SelfInfo, new RecordItemIndex(34));
            repo.DEMOQA.Self.MoveTo("1910;212");
            repo.DEMOQA.Self.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DEMOQA' at 1901;397.", repo.DEMOQA.SelfInfo, new RecordItemIndex(35));
            repo.DEMOQA.Self.MoveTo("1901;397");
            repo.DEMOQA.Self.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DEMOQA.DoubleClickBtn' at 100;41.", repo.DEMOQA.DoubleClickBtnInfo, new RecordItemIndex(36));
            repo.DEMOQA.DoubleClickBtn.DoubleClick("100;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'DEMOQA.RightClickBtn' at 105;32.", repo.DEMOQA.RightClickBtnInfo, new RecordItemIndex(37));
            repo.DEMOQA.RightClickBtn.Click(System.Windows.Forms.MouseButtons.Right, "105;32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA.NEyDU' at 96;34.", repo.DEMOQA.NEyDUInfo, new RecordItemIndex(38));
            repo.DEMOQA.NEyDU.Click("96;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DEMOQA' at 1910;389.", repo.DEMOQA.SelfInfo, new RecordItemIndex(39));
            repo.DEMOQA.Self.Click("1910;389");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
